---
title: "Upset plot and Circos plots"
author: "Sandra de Haan & Jingyan He"
date: "2025-01-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

####final upset and circos
#with subcluster info


```{r}

library(dplyr)
library(readr)
library(UpSetR)
library(Seurat)
library(dplyr)
library(ggplot2)
library(patchwork)
library(circlize)
library(scales)
```


```{r}
getwd()
```


```{r prepare tables for upset plot E9E10 with subcluster info}
df <- read.csv ("upset_wb_Sandra_28_multi.csv")
df
colnames(df) <- c("cloneid","celltype")
# generate a dataframe where seurat clusters are columns and clone id rows
for_upset <- df

for_upset #14461

# file for UpsetPlot contains 0 and 1 values.
#The rep() function is used to create a vector of repeated values. 
# all the rows in the "value" column of the "for_upset_AC" data frame will have the value of 1.

for_upset $ value <- rep(1, 14461)
#pivot_wider() function from the tidyr package to transform a data frame from long to wide format.
upset <- tidyr::pivot_wider(for_upset, names_from = celltype,
                   values_from = value, values_fn = sum, values_fill = 0)

#check
upset#4963 clones

write.csv(upset,file = "table_for_UpsetPlot_E9E10.with.subcluster.csv")
```

```{r upset plot, fig.height6, fig.width=35}
upset_corr <- read.csv(file ="table_for_UpsetPlot_E9E10.with.subcluster.csv")
upset_corr
# plot

Upsetplot <-upset(upset_corr,nsets=30, nintersects =500,  keep.order=T, order.by = "freq", number.angles = 30, mb.ratio = c(0.5, 0.5),  main.bar.color ="black", matrix.color = "black", shade.color = "lightgray", shade.alpha = 0.8, text.scale = c(2, 2, 2, 2, 2, 2))
Upsetplot

```


```{r prepare tables for circos plot}
upset_corr <- read.csv(file ="table_for_UpsetPlot_E9E10.with.subcluster_corrected.csv")
upset_corr #4963 rows

# Create an empty list to store the filtered dataframes
filtered_dfs <- list()

# Iterate over all possible combinations of two columns
for (i in 2:(ncol(upset_corr) - 1)) {
  for (j in (i + 1):ncol(upset_corr)) {
    # Filter the dataframe based on the condition
    filtered_df <- upset_corr[upset_corr[, i] == 1 & upset_corr[, j] == 1, ]
    # Store the filtered dataframe in the list
    if (nrow(filtered_df) > 0) {
      filtered_dfs[[paste0("col", i, "_col", j)]] <- filtered_df}}
}

# Create a new dataframe with the row counts
row_counts <- sapply(filtered_dfs, nrow)

new_df <- data.frame(value = row_counts)
new_df
#then we add a new column 
new_df $ clusters <- rownames(new_df)

#then we separate this column into two columns

library(tidyr)
# Separate the column into two columns using "_"
new_df <- separate(new_df, clusters, into = c("from", "to"), sep = "_")
new_df

# Replace values in the dataframe
new_df <- new_df %>%
  mutate(
    across(c(from, to), ~ case_when(
      . == "col2" ~ "0",
      . == "col3" ~ "1",
      . == "col4" ~ "2",
      . == "col5" ~ "3",
      . == "col6" ~ "4",
      . == "col7" ~ "5",
      . == "col8" ~ "6",
      . == "col9" ~ "7",
      . == "col10" ~ "8",
      . == "col11" ~ "9",
      . == "col12" ~ "10",
      . == "col13" ~ "11",
      . == "col14" ~ "12",
      . == "col15" ~ "13",
      . == "col16" ~ "14",
      . == "col17" ~ "15",
      . == "col18" ~ "16",
      . == "col19" ~ "19",
       . == "col20" ~ "20",
       . == "col21" ~ "21",
       . == "col22" ~ "22",
       . == "col23" ~ "23",
       . == "col24" ~ "25",
       . == "col25" ~ "26",
       . == "col26" ~ "27",
      . == "col27" ~ "29",
      . == "col28" ~ "30",
       . == "col29" ~ "31",
       . == "col30" ~ "100",
       . == "col31" ~ "200",
      . == "col32" ~ "300",
      TRUE ~ as.character(.)
    ))
  )

#check
new_df
#then re-arrange the columns
new_df <- new_df[,c("from","to","value")]
```

```{r self link E9E10.with.subcluster circosplot }

upset_corr

#add a sum column 
upset_corr$ sum <- rowSums(upset_corr[, 2:32])
upset_corr


#Then we filter the co-occurrence only happens within each cluster itself
x0 <- upset_corr%>% filter(X0==1)%>% filter(sum==1)
x1 <- upset_corr%>% filter(X1==1)%>% filter(sum==1)
x2 <- upset_corr%>% filter(X2==1)%>% filter(sum==1)
x3 <- upset_corr%>% filter(X3==1)%>% filter(sum==1)
x4 <- upset_corr%>% filter(X4==1)%>% filter(sum==1)
x5 <- upset_corr%>% filter(X5==1)%>% filter(sum==1)
x6 <- upset_corr%>% filter(X6==1)%>% filter(sum==1)
x7 <- upset_corr%>% filter(X7==1)%>% filter(sum==1)
x8 <- upset_corr%>% filter(X8==1)%>% filter(sum==1)
x9 <- upset_corr%>% filter(X9==1)%>% filter(sum==1)
x10 <- upset_corr%>% filter(X10==1)%>% filter(sum==1)
x11 <- upset_corr%>% filter(X11==1)%>% filter(sum==1)
x12 <- upset_corr%>% filter(X12==1)%>% filter(sum==1)
x13 <- upset_corr%>% filter(X13==1)%>% filter(sum==1)
x14 <- upset_corr%>% filter(X14==1)%>% filter(sum==1)
x15 <- upset_corr%>% filter(X15==1)%>% filter(sum==1)
x16 <- upset_corr%>% filter(X16==1)%>% filter(sum==1)
#x17 <- upset_corr%>% filter(X17==1)%>% filter(sum==1)
#x18 <- upset_corr%>% filter(X18==1)%>% filter(sum==1)
x19 <- upset_corr%>% filter(X19==1)%>% filter(sum==1)
x20 <- upset_corr%>% filter(X20==1)%>% filter(sum==1)
x21 <- upset_corr%>% filter(X21==1)%>% filter(sum==1)
x22 <- upset_corr%>% filter(X22==1)%>% filter(sum==1)
x23 <- upset_corr%>% filter(X23==1)%>% filter(sum==1)
#x24 <- upset_corr%>% filter(X24==1)%>% filter(sum==1)
x25 <- upset_corr%>% filter(X25==1)%>% filter(sum==1)
x26 <- upset_corr%>% filter(X26==1)%>% filter(sum==1)
x27 <- upset_corr%>% filter(X27==1)%>% filter(sum==1)
#x28 <- upset_corr%>% filter(X28==1)%>% filter(sum==1)
x29 <- upset_corr%>% filter(X29==1)%>% filter(sum==1)
x30 <- upset_corr%>% filter(X30==1)%>% filter(sum==1)
x31 <- upset_corr%>% filter(X31==1)%>% filter(sum==1)
x100 <- upset_corr%>% filter(X100==1)%>% filter(sum==1)
x200 <- upset_corr%>% filter(X200==1)%>% filter(sum==1)
x300 <- upset_corr%>% filter(X300==1)%>% filter(sum==1)



#the we generate a list of dataframe
df_list <- list(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x19,x20,x21,x22,x23,x25,x26,x27,x29,x30,x31,x100,x200,x300)
df_list
#then we can quickly extract the row number information
# Get the number of rows from each dataframe
row_counts <- lapply(df_list, nrow)
row_counts

# Create a new dataframe with the row counts, unlist to convert the list to a vector
value <-  unlist(row_counts)
value
#then add these values to circos table

from <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,25,26,27,29,30,31,100,200,300)
from
to <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,25,26,27,29,30,31,100,200,300)

df_x <- data.frame(from,to,value)
df_x
new_df

#then we bind the dataframes
for_circos <- rbind(df_x, new_df)
for_circos

write.csv(for_circos,file="for_circos_E9E10.with.subcluster.csv")
```


```{r E9E10.with.subcluster circos, fig.height=8, fig.width=8}
for_circos <- read.csv("for_circos_E9E10.with.subcluster.csv")
for_circos #288 

chordDiagram(for_circos, transparency = 0, link.arr.type = "big.arrow")

grid.color_highlight <- c('11'= "#F8DE7E",  # light yellow
    '12'= "#F4BB44",  # muted yellow
    '21'= "#FFAA33",  # amber yellow
    '19'= "#DAA520",  # goldenrod yellow
    '9'="#FFC107",   # sunflower yellow 

    # Shades of Green
    '25'= "#45B330",  # spring green
    '22'= "#0BF245",  # bright green
    '14'= "#90EE90",  # light green
    '8'= "#2E8B57",  # sea green
    '0'=  "#556B2F",  # olive green
    '15'= "#6C8E68",  # muted green 

    # Shades of Blue
    '200'= "#64B5F6",  # sky blue
    '300'= "#42A5F5",  # light blue
    '20'="#64B5F6",   # sky blue
    '10'="#42A5F5",   # light blue
    '3'=  "#1E88E5",   # cobalt blue
    '2'=  "#1976D2",   # medium blue
    '4'=  "#6495ED",   # cornflower blue
    '7'=  "#0D47A1",   # dark blue
    '1'=  "#4682B4",   # steel blue 

    # Shades of Purple
    '100'= "#800080",  # purple
    '27'= "#9370DB",   # medium purple

    # Shades of Brown
    '5'=  "#8D6E63",  # muted brown
    '23'= "#6D4C41",  # milk chocolate brown
    '13'= "#5D4037",  # walnut brown
    '30'= "#2C1B18"  # dark espresso brown
)
order_of_celltype_E9E10 <- c('5', '29', '31',  '23',
               '16',  '9', '12', '19', '11', '21',
                '0', '8', '14', 
                '22', '25','15',  '200', '300','1', '3', '10', '20', '2', '7', '4','6', '27', '100', '13', '30', 
                '26')
#then we can highlight stm and other cluster of interest, the reset in grey
chordDiagram(for_circos,transparency = 0, link.arr.type = "big.arrow")
chordDiagram(for_circos,transparency = 0, order=order_of_celltype_E9E10, link.arr.type = "big.arrow")

chordDiagram(for_circos,grid.col = grid.color_highlight, order =order_of_celltype_E9E10, transparency = 0, link.arr.type = "big.arrow")

```



###with otic remaining

```{r prepare tables for upset plot E9E10 with subcluster info}
df <- read.csv ("with_otic_remaining.csv")
df #14461 rows
colnames(df) <- c("cloneid","celltype")
# generate a dataframe where seurat clusters are columns and clone id rows
for_upset <- df

for_upset #14461

# file for UpsetPlot contains 0 and 1 values.
#The rep() function is used to create a vector of repeated values. 
# all the rows in the "value" column of the "for_upset_AC" data frame will have the value of 1.

for_upset $ value <- rep(1, 14461)
#pivot_wider() function from the tidyr package to transform a data frame from long to wide format.
upset <- tidyr::pivot_wider(for_upset, names_from = celltype,
                   values_from = value, values_fn = sum, values_fill = 0)

#check
upset#4963 clones

write.csv(upset,file = "table_for_UpsetPlot_E9E10.with.otic_remaining.csv")
```



```{r E9E10.with.otic. remaining circos plot}
upset_corr <- read.csv(file ="table_for_UpsetPlot_E9E10.with.otic_remaining_corrected.csv")
upset_corr #4963 rows

# Create an empty list to store the filtered dataframes
filtered_dfs <- list()

# Iterate over all possible combinations of two columns
for (i in 2:(ncol(upset_corr) - 1)) {
  for (j in (i + 1):ncol(upset_corr)) {
    # Filter the dataframe based on the condition
    filtered_df <- upset_corr[upset_corr[, i] == 1 & upset_corr[, j] == 1, ]
    # Store the filtered dataframe in the list
    if (nrow(filtered_df) > 0) {
      filtered_dfs[[paste0("col", i, "_col", j)]] <- filtered_df}}
}

# Create a new dataframe with the row counts
row_counts <- sapply(filtered_dfs, nrow)

new_df <- data.frame(value = row_counts)
new_df
#then we add a new column 
new_df $ clusters <- rownames(new_df)

#then we separate this column into two columns

library(tidyr)
# Separate the column into two columns using "_"
new_df <- separate(new_df, clusters, into = c("from", "to"), sep = "_")
new_df

# Replace values in the dataframe
new_df <- new_df %>%
  mutate(
    across(c(from, to), ~ case_when(
      . == "col2" ~ "0",
      . == "col3" ~ "1",
      . == "col4" ~ "2",
      . == "col5" ~ "3",
      . == "col6" ~ "4",
      . == "col7" ~ "5",
      . == "col8" ~ "6",
      . == "col9" ~ "7",
      . == "col10" ~ "8",
      . == "col11" ~ "9",
      . == "col12" ~ "10",
      . == "col13" ~ "11",
      . == "col14" ~ "12",
      . == "col15" ~ "14",
      . == "col16" ~ "15",
      . == "col17" ~ "16",
      . == "col18" ~ "19",
      . == "col19" ~ "20",
       . == "col20" ~ "21",
       . == "col21" ~ "22",
       . == "col22" ~ "23",
       . == "col23" ~ "25",
       . == "col24" ~ "27",
       . == "col25" ~ "29",
       . == "col26" ~ "31",
      . == "col27" ~ "100",
      . == "col28" ~ "200",
       . == "col29" ~ "300",
       . == "col30" ~ "400",
       . == "col31" ~ "500",
      TRUE ~ as.character(.)
    ))
  )

#check
new_df
#then re-arrange the columns
new_df <- new_df[,c("from","to","value")]
```


```{r self link E9E10.with.subcluster circosplot }

upset_corr

#add a sum column 
upset_corr$ sum <- rowSums(upset_corr[, 2:31])
upset_corr


#Then we filter the co-occurrence only happens within each cluster itself
x0 <- upset_corr%>% filter(X0==1)%>% filter(sum==1)
x1 <- upset_corr%>% filter(X1==1)%>% filter(sum==1)
x2 <- upset_corr%>% filter(X2==1)%>% filter(sum==1)
x3 <- upset_corr%>% filter(X3==1)%>% filter(sum==1)
x4 <- upset_corr%>% filter(X4==1)%>% filter(sum==1)
x5 <- upset_corr%>% filter(X5==1)%>% filter(sum==1)
x6 <- upset_corr%>% filter(X6==1)%>% filter(sum==1)
x7 <- upset_corr%>% filter(X7==1)%>% filter(sum==1)
x8 <- upset_corr%>% filter(X8==1)%>% filter(sum==1)
x9 <- upset_corr%>% filter(X9==1)%>% filter(sum==1)
x10 <- upset_corr%>% filter(X10==1)%>% filter(sum==1)
x11 <- upset_corr%>% filter(X11==1)%>% filter(sum==1)
x12 <- upset_corr%>% filter(X12==1)%>% filter(sum==1)
#x13 <- upset_corr%>% filter(X13==1)%>% filter(sum==1)
x14 <- upset_corr%>% filter(X14==1)%>% filter(sum==1)
x15 <- upset_corr%>% filter(X15==1)%>% filter(sum==1)
x16 <- upset_corr%>% filter(X16==1)%>% filter(sum==1)
#x17 <- upset_corr%>% filter(X17==1)%>% filter(sum==1)
#x18 <- upset_corr%>% filter(X18==1)%>% filter(sum==1)
x19 <- upset_corr%>% filter(X19==1)%>% filter(sum==1)
x20 <- upset_corr%>% filter(X20==1)%>% filter(sum==1)
x21 <- upset_corr%>% filter(X21==1)%>% filter(sum==1)
x22 <- upset_corr%>% filter(X22==1)%>% filter(sum==1)
x23 <- upset_corr%>% filter(X23==1)%>% filter(sum==1)
#x24 <- upset_corr%>% filter(X24==1)%>% filter(sum==1)
x25 <- upset_corr%>% filter(X25==1)%>% filter(sum==1)
#x26 <- upset_corr%>% filter(X26==1)%>% filter(sum==1)
x27 <- upset_corr%>% filter(X27==1)%>% filter(sum==1)
#x28 <- upset_corr%>% filter(X28==1)%>% filter(sum==1)
x29 <- upset_corr%>% filter(X29==1)%>% filter(sum==1)
#x30 <- upset_corr%>% filter(X30==1)%>% filter(sum==1)
x31 <- upset_corr%>% filter(X31==1)%>% filter(sum==1)
x100 <- upset_corr%>% filter(X100==1)%>% filter(sum==1)
x200 <- upset_corr%>% filter(X200==1)%>% filter(sum==1)
x300 <- upset_corr%>% filter(X300==1)%>% filter(sum==1)
x400 <- upset_corr%>% filter(X400==1)%>% filter(sum==1)
x500 <- upset_corr%>% filter(X500==1)%>% filter(sum==1)


#the we generate a list of dataframe
df_list <- list(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x14,x15,x16,x19,x20,x21,x22,x23,x25,x27,x29,x31,x100,x200,x300,x400,x500)
df_list
#then we can quickly extract the row number information
# Get the number of rows from each dataframe
row_counts <- lapply(df_list, nrow)
row_counts

# Create a new dataframe with the row counts, unlist to convert the list to a vector
value <-  unlist(row_counts)
value
#then add these values to circos table

from <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,19,20,21,22,23,25,27,29,31,100,200,300,400,500)
from
to <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,19,20,21,22,23,25,27,29,31,100,200,300,400,500)

df_x <- data.frame(from,to,value)
df_x
new_df

#then we bind the dataframes
for_circos <- rbind(df_x, new_df)
for_circos

write.csv(for_circos,file="for_circos_E9E10.with.otic_remaining.csv")
```


```{r E9E10.with.subcluster circos, fig.height=8, fig.width=8}
for_circos <- read.csv("for_circos_E9E10.with.otic_remaining.csv")
for_circos #278


chordDiagram(for_circos, transparency = 0, link.arr.type = "big.arrow")

grid.color_highlight_otic <- c('11'= "#F8DE7E",  # light yellow
    '12'= "#F4BB44",  # muted yellow
    '21'= "#FFAA33",  # amber yellow
    '19'= "#DAA520",  # goldenrod yellow
    '9'="#FFC107",   # sunflower yellow 

    # Shades of Green
    '25'= "#45B330",  # spring green
    '22'= "#0BF245",  # bright green
    '14'= "#90EE90",  # light green
    '8'= "#2E8B57",  # sea green
    '0'=  "#556B2F",  # olive green
    '15'= "#6C8E68",  # muted green 

    # Shades of Blue
    '200'= "#64B5F6",  # sky blue
    '300'= "#42A5F5",  # light blue
    '20'="#64B5F6",   # sky blue
    '10'="#42A5F5",   # light blue
    '3'=  "#1E88E5",   # cobalt blue
    '2'=  "#1976D2",   # medium blue
    '4'=  "#6495ED",   # cornflower blue
    '7'=  "#0D47A1",   # dark blue
    '1'=  "#4682B4",   # steel blue 

    # Shades of Purple
    '100'= "#800080",  # purple
    '27'= "#9370DB",   # medium purple

    # Shades of Brown
    '5'=  "#8D6E63",  # muted brown
    '23'= "#6D4C41",  # milk chocolate brown
    '500'= "#5D4037",  # walnut brown
    '400'= "#2C1B18"  # dark espresso brown
)

order_of_celltype_E9E10_otic <- c('5', '29', '31',  '23',
               '16',  '9', '12', '19', '11', '21',
                '0', '8', '14', 
                '22', '25','15',  '200', '300','1', '3', '10', '20', '2', '7', '4','6', '27', '100', '500', '400', 
                '26')

# Assume 'for_circos' is your input data frame for the chord diagram

# Add a column to define the link colors as red
for_circos$link_color <- ifelse(for_circos$from == 500 | for_circos$to == 500, "red", "lightgrey")

# Create the chord diagram with customized link colors
chordDiagram(
  x = for_circos,
  order = order_of_celltype_E9E10_otic,
  transparency = 0,
  grid.col = grid.color_highlight_otic,
  link.arr.type = "big.arrow",
  col = for_circos$link_color,
   annotationTrack =  c("name", "grid"),
  preAllocateTracks = 1 
)

# Create the chord diagram with customized link colors
chordDiagram(
  x = for_circos,
  order = order_of_celltype_E9E10_otic,
  transparency = 0,
  grid.col = grid.color_highlight_otic,
  link.arr.type = "big.arrow",
  col = for_circos$link_color,
  annotationTrack = "grid",        # Add grid annotation for labels
  preAllocateTracks = 1           # Pre-allocate a track for text labels
)

# Add curved text labels
chordDiagram(
  x = for_circos,
  order = order_of_celltype_E9E10_otic,
  transparency = 0,
  grid.col = grid.color_highlight_otic,
  link.arr.type = "big.arrow",
  col = for_circos$link_color,
  annotationTrack = c("name", "grid"),   # Automatically adds labels that follow the curve
  preAllocateTracks = 1
)

#then we can highlight stm and other cluster of interest, the reset in grey

chordDiagram(for_circos,grid.col = grid.color_highlight_otic, order =order_of_celltype_E9E10_otic, transparency = 0, link.arr.type = "big.arrow")

```



